export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';

export const QUESTION_REQUEST = 'QUESTION_REQUEST';
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';
export const QUESTION_FAILURE = 'QUESTION_FAILURE';

export const QUESTION_SUBMIT_REQUEST = 'QUESTION_SUBMIT_REQUEST';
export const QUESTION_SUBMIT_SUCCESS = 'QUESTION_SUBMIT_SUCCESS';
export const QUESTION_SUBMIT_FAILURE = 'QUESTION_SUBMIT_FAILURE';

export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST';
export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS';
export const QUESTION_LIST_FAILURE = 'QUESTION_LIST_FAILURE';

export const QUESTION_PROPERTIES_REQUEST = 'QUESTION_PROPERTIES_REQUEST';
export const QUESTION_PROPERTIES_SUCCESS = 'QUESTION_PROPERTIES_SUCCESS';
export const QUESTION_PROPERTIES_FAILURE = 'QUESTION_PROPERTIES_FAILURE';
