// initial:

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// problems:

export const GET_PROBLEM_REQUEST = 'GET_PROBLEM_REQUEST';
export const GET_PROBLEM_SUCCESS = 'GET_PROBLEM_SUCCESS';
export const GET_PROBLEM_FAILURE = 'GET_PROBLEM_FAILURE';

export const SUBMIT_PROBLEM_REQUEST = 'SUBMIT_PROBLEM_REQUEST';
export const SUBMIT_PROBLEM_SUCCESS = 'SUBMIT_PROBLEM_SUCCESS';
export const SUBMIT_PROBLEM_FAILURE = 'SUBMIT_PROBLEM_FAILURE';

export const PROBLEM_LIST_REQUEST = 'PROBLEM_LIST_REQUEST';
export const PROBLEM_LIST_SUCCESS = 'PROBLEM_LIST_SUCCESS';
export const PROBLEM_LIST_FAILURE = 'PROBLEM_LIST_FAILURE';

// properties:

export const TAGS_REQUEST = 'TAGS_REQUEST';
export const TAGS_SUCCESS = 'TAGS_SUCCESS';
export const TAGS_FAILURE = 'TAGS_FAILURE';

export const SUBTAGS_REQUEST = 'SUBTAGS_REQUEST';
export const SUBTAGS_SUCCESS = 'SUBTAGS_SUCCESS';
export const SUBTAGS_FAILURE = 'SUBTAGS_FAILURE';

export const EVENTS_REQUEST = 'EVENTS_REQUEST';
export const EVENTS_SUCCESS = 'EVENTS_SUCCESS';
export const EVENTS_FAILURE = 'EVENTS_FAILURE';

export const SOURCES_REQUEST = 'SOURCES_REQUEST';
export const SOURCES_SUCCESS = 'SOURCES_SUCCESS';
export const SOURCES_FAILURE = 'SOURCES_FAILURE';

// account:

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';

export const SHOWـPROMPT = 'SHOWـPROMPT';
export const REMOVEـPROMPT = 'REMOVEـPROMPT';
