export const UPDATE_QUESTION_DATA_REQUEST = 'UPDATE_QUESTION_DATA_REQUEST';
export const UPDATE_QUESTION_DATA_RECEIVE = 'UPDATE_QUESTION_DATA_RECEIVE';
export const UPDATE_QUESTION_LIST_REQUEST = 'UPDATE_QUESTION_LIST_REQUEST';
export const UPDATE_QUESTION_LIST_RECEIVE = 'UPDATE_QUESTION_LIST_RECEIVE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGOUT = 'LOGOUT';
